input {
	file {
		path => "/usr/share/logstash/input/previously_searched_sample.json"
		start_position => "beginning"
		sincedb_path => "/dev/null"
		codec => json
		ecs_compatibility => "disabled"
	}
}

filter {
	mutate {
		rename => {}
		remove_field => ["host", "log", "event"]
	}

	ruby {
	code => '
		# Increment search_count
		count = event.get("search_count") || 0
		event.set("search_count", count + 1)

		# Normalize search_text
		search_text = event.get("search_text")
		search_text = search_text ? search_text.strip.downcase : ""
		event.set("search_text", search_text)

		# Set the document Id
		identifier = event.get("email") || event.get("phone_number")
		normalized_id = identifier ? identifier.strip.downcase : ""
		id = normalized_id + "-" + search_text
		id = id.gsub(/\s+/, "_")
		event.set("doc_id", id)

		# Set timestamps
		now = Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%LZ")
		# event.set("created_date", now) unless event.get("created_date")
		event.set("updated_at", now)
	'
	}
}

output {
stdout { codec => rubydebug }
	elasticsearch {
		"hosts" => "${ELASTICSEARCH_HOSTS}"
		"user" => "${ELASTICSEARCH_USERNAME}"
		"password" => "${ELASTICSEARCH_PASSWORD}"
		"index" => "${PREVIOUSLY_SEARCHED_ITEM_INDEX_NAME}"
		"document_id" => "%{doc_id}"
		"ssl_enabled" => true
		"ssl_certificate_authorities" => "${CA_CERTIFICATE_PATH}"
		"action" => "update"
		"doc_as_upsert" => true
		"manage_template" => false
	}
}
