input {
	file {
		path => "/usr/share/logstash/input/product_search_sample.json"
		start_position => "beginning"
		sincedb_path => "/dev/null"
		codec => json
		ecs_compatibility => "disabled"
	}
}

filter {
	mutate {
		remove_field => ["host", "log", "event"]
	}

	ruby {
	code => '
		# Increment search_count
		count = event.get("search_count") || 0
		event.set("search_count", count + 1)

		# Set timestamps
		now = Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%LZ")
		event.set("created_at", now) unless event.get("created_at")
		event.set("updated_at", now)

		# Set the document Id
		id = event.get("product_id")
		if id.nil?
			event.tag("missing_product_id")
		else
			event.set("doc_id", id)
		end
	'
	}

	if "missing_product_id" in [tags] {
		drop { }
	}
}

output {
stdout { codec => rubydebug }
	elasticsearch {
		"hosts" => "${ELASTICSEARCH_HOSTS}"
		"user" => "${ELASTICSEARCH_USERNAME}"
		"password" => "${ELASTICSEARCH_PASSWORD}"
		"index" => "${PRODUCT_SEARCH_INDEX_NAME}"
		"document_id" => "%{doc_id}"
		"ssl_enabled" => true
		"ssl_certificate_authorities" => "${CA_CERTIFICATE_PATH}"
		"action" => "update"
		"doc_as_upsert" => true
		"manage_template" => false
	}
}
